### ISSUE TITLE
Not working with id3v2 0.1.12

### ISSUE THREAD

**Issue by ticalc-travis** [goodevilgenius/tagedit#4]
tagedit doesn't appear to work with id3v2 0.1.12 (at least the version on SourceForge at https://sourceforge.net/projects/id3v2/files/). It appears that the -R option that it uses was removed in that version of id3v2. The result of trying to use it with MP3 files in that case is that it generates a list of filenames in the text file, but no tags.

**Comment by goodevilgenius** [comment]
I have version 0.1.12, and it does support the `-R` flag. Unfortunately, I need it because the output format is unpredictable with `-l`, and I need a predictable output in order to parse it.

So, you'll need to find a version that supports it. I've used tagedit with id3v2 0.1.12 on both Ubuntu and Fedora, and it works on both. It's likely a configuration option that's not being used in the version on sourceforge.

**Comment by ticalc-travis** [comment]
Weird. I had assumed the SF version was the “canonical” one (it's used as the upstream source in Arch Linux), but when I look around, there does seem to be a number of random forks of it, some of which have the code for the option, some of which have it removed, which is sort of confusing. :-)

**Comment by ziotom78** [comment]
For the record, I confirm the same problem occurs with the "id3v2" executable currently provided by Linux Manjaro 18.1.5:

```
$ id3v2 --version
id3v2 0.1.12
Uses id3lib-3.8.3

This program adds/modifies/removes/views id3v2 tags, 
and can convert from id3v1 tags

$  id3v2 --help
Usage: id3v2 [OPTION]... [FILE]...
Adds/Modifies/Removes/Views id3v2 tags, modifies/converts/lists id3v1 tags

  -h,  --help               Display this help and exit
  -f,  --list-frames        Display all possible frames for id3v2
  -L,  --list-genres        Lists all id3v1 genres
  -v,  --version            Display version information and exit
  -l,  --list               Lists the tag(s) on the file(s)
  -d,  --delete-v2          Deletes id3v2 tags
  -s,  --delete-v1          Deletes id3v1 tags
  -D,  --delete-all         Deletes both id3v1 and id3v2 tags
  -C,  --convert            Converts id3v1 tag to id3v2
  -1,  --id3v1-only         Writes only id3v1 tag
  -2,  --id3v2-only         Writes only id3v2 tag
  -r,  --remove-frame "FRAMEID"   Removes the specified id3v2 frame
  -a,  --artist       "ARTIST"    Set the artist information
  -A,  --album        "ALBUM"     Set the album title information
  -t,  --song         "SONG"      Set the song title information
  -c,  --comment      "DESCRIPTION":"COMMENT":"LANGUAGE"  
                            Set the comment information (both
                            description and language optional)
  -g,  --genre   num        Set the genre number
  -y,  --year    num        Set the year
  -T,  --track   num/num    Set the track number/(optional) total tracks

You can set the value for any id3v2 frame by using '--' and then frame id
For example: 
        id3v2 --TIT3 "Monkey!" file.mp3
would set the "Subtitle/Description" frame to "Monkey!". 
```

The commit to blame for this is [4bf36b](https://github.com/nagilo/id3v2/commit/4bf36bcd33b6c89ea1c9bf514423424990a7643e). The name of the commit is deceiving ("Turned on all gcc warnings and removed them (minor changes)"), because the comment says

> Additionally removed rfc822 conform list flag since it has not been used.

Really annoying!

**Comment by goodevilgenius** [comment]
@ziotom78 Yeah, I don't have it on Fedora anymore either.

I don't really use `tagedit` anymore, so I'm not particularly inclined to fix this, but I'm open to a PR from someone else who wants to fix it.

It might require a different program than `id3v2`. `id3info` might fit the bill.
